#!/bin/bash

if [ -z "$SCREEN_SIZE" ]; then SCREEN_SIZE=1280x720; fi

Xtigervnc :0 -geometry $SCREEN_SIZE -depth 24 -rfbport 5900 -SecurityTypes None &
VNCPID=$!

export DISPLAY=:0
export SHELL=/bin/bash
sleep 1
xrdb -load ~/.Xdefaults
dbus-run-session -- startfluxbox &
FLUXBOXPID=$!

echo
echo " * To connect there, run: vncviewer 127.0.0.1"
echo " * Press Ctrl-C to stop container"
tail --pid=$FLUXBOXPID -f /dev/null

kill $VNCPID
