#!/bin/bash

Xtigervnc :0 -geometry 1280x720 -depth 24 -rfbport 5900 -SecurityTypes None &
VNCPID=$!

export DISPLAY=:0
export SHELL=/bin/bash
xrdb -load ~/.Xdefaults
dbus-run-session -- startfluxbox &
FLUXBOXPID=$!

sleep 1
echo
echo " * To connect there, run: vncviewer 127.0.0.1"
echo " * Press Ctrl-C to stop container"
tail --pid=$FLUXBOXPID -f /dev/null

kill $VNCPID
